export const TODOLIST_FETCH_LIST_SUCCESS = 'TODOLIST_FETCH_LIST_SUCCESS';
export const TODOLIST_FETCH_LIST = 'TODOLIST_FETCH_LIST';
export const TODOLIST_FETCH_STATUS_ENUM = 'TODOLIST_FETCH_STATUS_ENUM';
export const TODOLIST_FETCH_STATUS_ENUM_SUCCESS =
  'TODOLIST_FETCH_STATUS_ENUM_SUCCESS';
export const TODOLIST_ADD_LIST = 'TODOLIST_ADD_LIST';
export const TODOLIST_ADD_LIST_SUCCESS = 'TODOLIST_ADD_LIST_SUCCESS';
export const TODOLIST_REMOVE_LIST = 'TODOLIST_REMOVE_LIST';
export const TODOLIST_LOADING_START = 'TODOLIST_LOADING_START';
export const TODOLIST_LOADING_END = 'TODOLIST_LOADING_END';
